"""Ajout de la colonne alert à la table Product

Revision ID: 06e7cb1e3e5d
Revises: be40c66a0c55
Create Date: 2025-08-09 06:06:11.737732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e7cb1e3e5d'
down_revision = 'be40c66a0c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('alert')

    # ### end Alembic commands ###
