"""Ajout de lignes d'adresse et de logo dans User

Revision ID: 38b296c6efb1
Revises: 3f37220a2d16
Create Date: 2025-06-25 03:07:20.863213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b296c6efb1'
down_revision = '3f37220a2d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('logo')
        batch_op.drop_column('adresse')

    # ### end Alembic commands ###
