"""Ajout du champ entreprise dans User

Revision ID: 3f37220a2d16
Revises: d77e48f5bbd4
Create Date: 2025-06-25 02:24:58.246158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f37220a2d16'
down_revision = 'd77e48f5bbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entreprise', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('entreprise')

    # ### end Alembic commands ###
