"""Ajout des colonnes de code unique à la table User

Revision ID: 41a226acbd65
Revises: f4aa9b81205c
Create Date: 2025-07-17 06:53:02.000423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a226acbd65'
down_revision = 'f4aa9b81205c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiration')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
