"""Ajout de la colonne 'parent_id' dans la table user

Revision ID: 555e41a6d1f6
Revises: 08e5674b330e
Create Date: 2025-07-07 18:02:59.424214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555e41a6d1f6'
down_revision = '08e5674b330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_parent', 'user', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_parent', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
