"""Ajout de la colonne sale_id dans la table Notification

Revision ID: 60a78b0830b2
Revises: e372ffda3590
Create Date: 2025-08-23 07:27:47.256109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a78b0830b2'
down_revision = 'e372ffda3590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_sale_id', 'sale', ['sale_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_sale_id', type_='foreignkey')
        batch_op.drop_column('sale_id')

    # ### end Alembic commands ###
