"""Ajout de la colonne 'parent_id' dans la table 'Products'

Revision ID: 8fac7e73ebcc
Revises: 7f74dcfd8e50
Create Date: 2025-07-09 18:42:04.586582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fac7e73ebcc'
down_revision = '7f74dcfd8e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('products_parent_id_fkey', 'user', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('products_parent_id_fkey', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
