"""Ajout de la colonne 'seller' dans la table 'Sales'

Revision ID: e4a5d3e661fa
Revises: 8fac7e73ebcc
Create Date: 2025-07-09 18:59:12.437847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a5d3e661fa'
down_revision = '8fac7e73ebcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller', sa.String(length=200), nullable=False, server_default='admin'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('seller')

    # ### end Alembic commands ###
