"""Ajout des jetons pour conseil IA dans la table 'User'

Revision ID: f4aa9b81205c
Revises: e4a5d3e661fa
Create Date: 2025-07-13 21:12:33.638032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4aa9b81205c'
down_revision = 'e4a5d3e661fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_conseil', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_token_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_token_reset')
        batch_op.drop_column('tokens_conseil')

    # ### end Alembic commands ###
